// Phase 1ではダミーデータでタイムラインを表示
// Supabase接続後に実データに切り替え

export const DUMMY_WALKS = [
  {
    id: '1',
    user: 'Hiroshi',
    avatar: '🧑',
    location: '代々木公園 → 原宿',
    distance: '3.2km',
    duration: '48分',
    photos: ['🌸', '🌿', '☕'],
    comment: '桜がもう少しで満開。来週が見頃かも。',
    likes: 24,
    time: '今日 8:32',
    tag: '🌸 桜',
    color: '#f9a8a8',
  },
  {
    id: '2',
    user: 'Mika',
    avatar: '👩',
    location: '等々力渓谷',
    distance: '2.1km',
    duration: '35分',
    photos: ['🌲', '💧'],
    comment: '都内とは思えない静けさ。犬連れにも最高でした。',
    likes: 41,
    time: '昨日',
    tag: '🐶 犬連れOK',
    color: '#a8d5a8',
  },
  {
    id: '3',
    user: 'Kenji',
    avatar: '🧔',
    location: '谷中 → 根津',
    distance: '4.5km',
    duration: '1時間12分',
    photos: ['🏠', '🐱', '🍜'],
    comment: '猫が多すぎてなかなか進めなかった。',
    likes: 88,
    time: '2日前',
    tag: '🐱 猫スポット',
    color: '#f5d6a8',
  },
  {
    id: '4',
    user: 'Yui',
    avatar: '👧',
    location: '下北沢 → 三軒茶屋',
    distance: '2.8km',
    duration: '42分',
    photos: ['☕', '🎨', '🌿'],
    comment: 'カフェ巡りしながらのんびり。古着屋も発見。',
    likes: 35,
    time: '3日前',
    tag: '☕ カフェ寄り道',
    color: '#d4b896',
  },
];
